# localhost "postgres://postgres:123456@localhost:5432/posts?sslmode=disable"
# server "postgres://posts:38S2GPNZut4Tmvan@dev.opensource-technology.com:5523/posts?sslmode=disable"
app:
  port: 8080

# db:
#   driver: postgres
#   host: localhost
#   username: postgres
#   database: posts
#   port: 5432
#   password: "123456"

db:
  driver: postgres
  host: dev.opensource-technology.com
  username: posts
  database: posts
  port: 5523
  password: 38S2GPNZut4Tmvan